### ISSUE TITLE
Prevent Overwriting. [Feature, not a bug]

### ISSUE THREAD

**Issue by noobcoder2196** [tharyckgusmao/Skill-Share-Crawler---DL#3]
Hey bro, you should really consider a check for existence of an already downloaded course and in that case skip the files for that course(s). It'd be especially helpful for category downloads because when I try to download a category, it doesn't resume from where it left off. It starts overwriting the already downloaded courses from the start. You think you can add this filecheck functionality?

**Comment by tharyckgusmao** [comment]
Very good, I think a great idea, at the beginning was with this intention to return the download of the moment that stopped, but I ended up leaving the project in the drawer, since already had downloaded everything I needed.

But I can implement this functionality and something quite simple.

If you want to do it and play a push for the project I commite it.
Thank you.

**Comment by noobcoder2196** [comment]
Sorry, but I dont know programming that much...could you do it please?

**Comment by Tasosgi** [comment]
I made the file check functionality. Do you want to check it?

**Comment by tharyckgusmao** [comment]
Yes we do. do the pull for the project.

**Comment by noobcoder2196** [comment]
Any update for the file check functionality?

**Comment by tharyckgusmao** [comment]
I am waiting for @Tasosgi  to push for the project.

**Comment by tharyckgusmao** [comment]
Check. Pull Request by @Tasosgi
